version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: unless-stopped

  php:
    image: php:7.4-cli
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app

  phpunit:
    image: php:7.4-cli
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit